apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weather.fullname" . }}
  labels:
    {{- include "weather.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "weather.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "weather.selectorLabels" . | nindent 8 }}
    spec:
      {{- if and .Values.podDns .Values.podDns.enabled }}
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          {{- range .Values.podDns.nameservers }}
          - {{ . | quote }}
          {{- end }}
        {{- if .Values.podDns.searches }}
        searches:
          {{- range .Values.podDns.searches }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
        {{- if .Values.podDns.options }}
        options:
          {{- range .Values.podDns.options }}
          - name: {{ .name | quote }}
            {{- if .value }}
            value: {{ .value | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
            - configMapRef:
                name: {{ .Values.configmap.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: graphs
              mountPath: /app/public
          livenessProbe:
            exec:
              command: ["sh", "-c", "test -f /app/index.html && test -z \"$(find /app/graphs -name '*.png' -mmin +62)\""]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3

          readinessProbe:
            exec:
              command: ["sh", "-c", "test -f /app/index.html && test -n \"$(ls /app/graphs/*.png 2>/dev/null)\""]
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 2
      volumes:
        - name: graphs
          emptyDir: {}
