apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telegram-proxy.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-proxy
  template:
    metadata:
      labels:
        app: telegram-proxy
    spec:
      containers:
        - name: proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
