# Образ
image:
  repository: asmnt/weather
  tag: "latest"          # будет переопределяться в CI
  pullPolicy: IfNotPresent

# Секреты (имя существующего Kubernetes Secret)
secrets:
  name: weather-secret  # ← должен существовать в кластере

# ConfigMap
config:
  # содержимое index.html или других конфигов можно передавать здесь,
  # но если у вас статический index.html — лучше включить его в образ
  # или монтировать отдельно. Пока оставим пустым.
  #

configmap:
  name: weather-config

# Ресурсы (опционально)
resources:
  limits:
    memory: "128Mi"
    cpu: "100m"
  requests:
    memory: "64Mi"
    cpu: "50m"

#podDns:
#  enabled: true
#  nameservers:
#    - "8.8.8.8"
#    - "1.1.1.1"
#  searches:
#    - "svc.cluster.local"
#    - "cluster.local"
#  options:
#    - name: "ndots"
#      value: "2"
#    - name: "timeout"
#      value: "2"

podDns:
  enabled: true
  nameservers:
    - "10.96.0.10"
  searches:
    - "default.svc.cluster.local"
    - "svc.cluster.local"
    - "cluster.local"
  options:
    - name: "ndots"
      value: "1"
    - name: "timeout"
      value: "2"
