server:
  persistentVolume:
    enabled: false
  retention: "6h"
  extraConfigmapMounts:
    - name: weather-rules
      mountPath: /etc/prometheus/rules.d/
      subPath: ""
      configMap: prometheus-weather-rules
      readOnly: true

serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/prometheus/rules.d/weather-alerts.yaml
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'telegraf'
        static_configs:
          - targets: ['telegraf:9273']
