server:
  persistentVolume:
    enabled: false
  retention: "6h"
  extraConfigmapMounts:
    - name: weather-rules
      mountPath: /etc/prometheus/rules.d/
      subPath: ""
      configMap: prometheus-weather-rules
      readOnly: true

serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/prometheus/rules.d/weather-alerts.yaml
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'telegraf'
        static_configs:
          - targets: ['telegraf:9273']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['prometheus-kube-state-metrics:8080']
      - job_name: 'weather-website'
        scrape_interval: 30m
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - https://exograph.neocities.org/graphs/weather-temperature_2m--2d.png
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-blackbox-exporter:9115

alertmanager:
  enabled: true
  persistentVolume:
    enabled: false
    size: 2Gi
    storageClass: ""  # без StorageClass — будет использовать ваш PV
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: 'telegram'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
    receivers:
      - name: 'telegram'
        webhook_configs:
          - url: 'http://telegram-proxy:8080/alert'
            send_resolved: true

#prometheus-blackbox-exporter:
#  enabled: true
#  service:
#    type: ClusterIP
